name: Python Code Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black pytest pytest-mock # <-- إضافة pytest-mock

      # --- بداية التعديل: تثبيت متصفح Playwright ---
      - name: Install Playwright Browsers
        run: playwright install chromium --with-deps
      # --- نهاية التعديل ---

      - name: Run tests (and skip UI tests)
        run: pytest -m "not ui"

      - name: Lint with ruff
        run: ruff check .

      - name: Check formatting with black
        run: black . --check